language: go
go:
  - 1.7.x
install:
  - make get-deps
script:
  - make get-test-data
  - make test
  - make build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: WTDPu9aLMCoCqHbq0A9sdIBx3PPW4vgPB6+bfgVdnU0g5b49v6ie0mSXCME46jO/fxkVuBT7qDijWrP4ZNQXM6lzmvEF9CqN11AIUGhaidGB2La6EnmLJP1BCjw3CKkQJws4jpdEp503i2RuIjcASrl3MxEF0djVJJQ+UJY/MRWicLugbPiRAxh9Jt2BCBfTN4Nhfz3d2EZPaz3DUr47+mvQ2+OmXbBKQz0p1Xp7n2As3WYuNgZT0wCFTDvvoNSJt+fK19QidMNzOxDnPlTjVGVTk6Ii6ScjIRhiNTCJLAj6PcaaHbAjXIXavOpWGRYakl4kKk7rFkIUKARsCTF9vbAiEqzkmxZia4jYczcDqpH07vzPg5oWkk6FbTPIGvgXMP9kBjHFYtI/xg4/cAMrwVO61xROB5OAFCLudBtTyeCLM/rbBZC6KtzVQH2pRkKbf43HiEYootIFcGj9EqyFbLVjv577Sw96ovZkITUmCVGlYKf79vQ5MS9JEKXoUX3MKgVQzKcBgd8li6Rz93ITlFtdOaMAcw3S3nqQbrdF8cIpfLMW3N1yePQuUh9aMMe4DS4ckYHSRgusPPvLLzhpN9DNXN/D8/16SHfQ2tlqwKJDgKh7SNvbHf4oT7CHMCiYHYEslFcCRxx6SjQNh1D+oJ1FkxHr5sn3RJvibT/qI5o=
  file: bin/jackdwyer
