language: go
go:
- 1.7.x
install:
- make get-deps
script:
- make get-test-data
- make test
- make build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: gac+TSOQDS9pXtYYsQu4DjD3DiVp7D3I3h0mcrO/Oio40prl4t0vyiCrYqfSObSGtwLPjLTHkc18cW/Nh+uAZ57ad43KMcUVQOMNCiMDWXsYkVnJJH+gpTGzuSmCbyrs/TZrswpn+Hmll/6KEgelR06m0vFQ/mqb5R6NvW1gzdJkJOsNPo869uSpUc76PXz3ixiXWBGpccqsUFG4PfdnaKJc4rtuxbClhndCuKvMwsBj03bhbmB7gdvwX3hSXJcHw+WtYmkMDNP70CmVfuIyh5Rk+XyxAc7QLbM6pYFIuHp4z8uFuT7Z0VxQGm08STehT51Cypt1UUcCBzdFxE8miBLo4gA5FRJNg1SSGJikv02m0hXgVSDj6tmyzCsP1tfmw9mcUig7wYPVARdZkpEnRcwYliM9gF3bEMWmtgYsJfqI087FAE9a9CEJ/nSzLzFS/PcrGsloyO/DxXBlqjU+Mu6g6VQaiFnEqmZ65w4bO4N1mz5tUMHNIsuCEH1tkdqEc7m1wtwk7UR1SPaFJHt8QRuSBbZHoh4sPgvNbhq7xcUSZXUAbwTJTZP9nZ8g4IvJM/X+ckc04ssJduEGBMAYuFFYmaRY1EncR0ohPbrBCSyYlt+v/YHbL+KxkCVwanfefeMWGu/H7dE1CjIfBtNjzbLGEFtOwLYaMMlahIhpRtg=
  file: bin/jackdwyer
  on:
    repo: jackdwyer/jackdwyer.org
